### ISSUE TITLE
switch to using entry_points in meta.yaml?

### ISSUE THREAD

**Issue by carlodri** [conda-forge/igor-feedstock#2]
rather than using `source_files` like this in the recipe:

```yaml
test:
  source_files:
    - bin/igorbinarywave.py
    - bin/igorpackedexperiment.py
  commands:
    - python bin/igorbinarywave.py  --help
    - python bin/igorpackedexperiment.py --help
```

should I rather switch to defining two `entry_points` to the relevant scripts?
